### PR TITLE
Add plugins to django-binder 

### PR DESCRIPTION
**Pull request by stefanmajoor**
In this pull request I added two additions to django-binder that are copied from SMS.

### ImageView
This is a view for models that have an image associated with them. This view makes a copy of the original image, and allows the user to do various actions on the image. (Rotating, Cropping, Resetting)

### CsvExportView
This view adds a new route to the modelview, namely `download`. This route behaves sort of like get collection (sorting, filtering), but rather downloads a predefined CSV file. This allows us to easily add a download csv button to a view.

Now there are two questions which rise from this:

1. Are these views useful in Binder? Are they generic enough that they can be used in other projects
2. How are we going to do plugin management? At this moment I just used multiple inheritance to load plugins. Maybe there is a better way to do this. Also, do we want to include the plugins in the main repo, or do we want to make additional repos for plugins?

If those questions are answered, I can clean up the code, and add more unit tests.

### CODE REVIEW

**Comment by SpaceK33z** [comment]
@stefanmajoor the CI is failing due to some flake8 issues, can you look into that?

**Comment by SpaceK33z** [comment]
Didn't see your last sentence at first. Anyway, some thoughts on keeping it in here vs separate repo:

- Advantage of separate repo;
  - Easier to do breaking changes
  - Keeps the django-binder core "tiny" (does this even matters in practice?) 
- Advantage of all-in-one approach:
  - Less repo overhead (at the moment there is quite a lot of boilerplate stuff necessary for testing, CI, etc.)
  - Easier to ensure plugins still run with the latest version of django-binder (since all tests are run at once)

Mostly because of the last point I'm leaning more towards doing it in this repo. Of course you could make tooling that runs the plugin tests with the latest `master` commit of django-binder, but I don't think anyone has time for that.

**Comment by stefanmajoor** [comment]
> Easier to do breaking changes

I disagree. If you do breaking changes, there are two possibilities. Either the changes do not affect the plugin, in which case it doesn't matter if the plugin is in a seperate plugins or not. In the other case, the changes affect the plugins. This means that before projects can be updated the plugins need to be updated too. I agree it is easier if we have a good versioning system, and still support older versions. This is not done at the moment, which means that if we want to update binder, we have to update all plugins anyway. 

I think the other point of that question is maybe more important to discuss first, how are we supporting extensions/plugins for binder? Are we going to specifically add hooks/etc? Or are we going in the "just use the existing interface" direction, like I did now?

**Comment by stefanmajoor** [comment]
I added a UserViewMixin and MasqueradeMixin too, and fixed all the flake8 errors. I believe it is now good for a merge.

**Comment by Daanvdk** [comment]
Add the moment the userview mixins have a dependency on `django-hijack` (`==2.1.4` in sms) that is not in the `setup.py`. Maybe because it is a plugin a full dependency wouldn't make sense but an [optional dependency](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) seems like a good idea. Also because the `UserViewMixin` and `MasqueradeMixin` share one file the `UserViewMixin` now also has this dependency while only the `MasqueradeMixin` actually uses it.

**Comment by mmoreaux** [comment]
I think the idea in general is fine, but I don't particularly like the CsvExport being a Mixin... It makes it relatively hard to customize (and I feel the `View.csv_settings` is a result of that). It also hardcodes the `/download/` endpoint.

The _only_ thing that Mixin does is add a list route; why not provide a method in the plugin, and simply define the route in your view, calling that method? Something like:

```
class FooView(BinderView):
    @list_route(name='download', methods=['GET'])
    def download(self, request):
        plugins.csv_export(self, request, foo=5, bar=plugins.csv_export.TYPE_LIST, baz=False)
```

Or even:

```
class FooView(BinderView):
    @list_route(name='differentname', methods=['GET'])
    def csv_export(self, request):
        plugins.csv_export(self, request, SomeCsvSettingsObject(foo=5))
```

(to be honest, I wonder how generic such an export can really be; in my experience such exports quickly evolve into "oh I need to link this field from related objects too" and "it needs a header" and "dates should be formatted thusly", quickly requiring custom code anyway)

**Comment by stefanmajoor** [comment]
The idea behind this was to make a very simple way to add a csv export to a model, which was consistent throughout the whole application. In this case it works with only setting the extending the `CsvExportView` and setting the `csv_settings`, which was enough for the intended purposes. If you do not like the structure of the plugin, I will just remove it from the PR.

> (to be honest, I wonder how generic such an export can really be; in my experience such exports quickly evolve into "oh I need to link this field from related objects too" and "it needs a header" and "dates should be formatted thusly", quickly requiring custom code anyway)

FWIW, all three examples are supported by this plugin.

**Pull request merged**
