### PR TITLE
Validation refactoring

### LINKED ISSUE #43: multi-put validation is short-circuited on first error
If you multi-put a main object plus a related object and the related object doesn't validate, Binder stops and reports the error on the related object.

It should continue and collect the validation errors of the main object, so the UI has an opportunity to show all the problems with a filled-in form rather than requiring a depth-first trial and error traversal through the tree of objects.

### LINKED ISSUE #59: Multi-PUT; support nested field validation errors
In TMS you have an `Order` model which has a one-to-many on `Activity`. The `Activity` has a field `house_number`, which is required. When performing a multi-PUT on the `Order`, without any data, you get this:

```json
{
  "error": {
    "validation_errors": {
      "house_number": [
        {
          "code": "This field cannot be null."
        }
      ]
    }
  },
  "code": "ValidationError"
}
```

You can see here that the `house_number` is not scoped to the activity. I would expect it to return something like this:

```json
{
  "error": {
    "validation_errors": {
      "activities[0].house_number": [
        {
          "code": "This field cannot be null."
        }
      ]
    }
  },
  "code": "ValidationError"
}
```

That way the frontend can map it precisely to a specific activity. Note that we also did it like this in our old PHP stack.

### LINKED ISSUE #62: Validation errors should return an actual code, not a message
```js
{
  "error": {
    "validation_errors": {
      "house_number": [
        {
          "code": "This field cannot be null."
        }
      ]
    }
  },
  "code": "ValidationError"
}
```

The field `code` in `house_number` says "This field cannot be null". But this is a message, not a code. The problem with this is that we have translations in the frontend, but we can't easily map that if such a message is used instead of a code. So we want to do the code -> message stuff completely in the frontend, where the translations live.

Note that perhaps some validation messages have dynamic values in them (something like "Field can be max `<integer>` characters long." Such values can be added to the same object where `code` lives in.

### PR DESCRIPTION
**Pull request by Daanvdk**
Refactored validation.
fixes #43 fixes #59 fixes #62 

In the code it said that django's full_clean does not check nullability so that we had to implement it ourselves, however during testing I found that I got double errors because django does seem to do it, so I just commented that part out. Maybe it was just in some specific situation that I am not aware of?

### CODE REVIEW

**Comment by mmoreaux** [comment]
@Daanvdk 
> In the code it said that django's full_clean does not check nullability so that we had to implement it ourselves, however during testing I found that I got double errors because django does seem to do it

Try again with `CharField(max_length=20, blank=True, null=False)`.

**Comment by JasperStam** [comment]
Why does `store_field` need a `pk`?

**Comment by SpaceK33z** [comment]
Found an issue after using this branch in TMS for a while. Suppose you have this code:

```python
class ContactPerson(BinderModel):
	name = models.TextField()

class Charter(BinderModel):
	contact_person = models.OneToOneField(ContactPerson)
```

When saving via multi-PUT to `api/charter`, the name of the with is `contact_person`. However, if the `name` field in `contact_person` has a validation error, it will return this:

```json
"errors": {
    "contactperson": {
      "-4": {
        "name": [
          {
            "message": "This field cannot be blank.",
            "code": "blank"
          }
        ]
      }
    }
}
```

As you can see here, the name of the relation is `contactperson`, not `contact_person`, as mobx-spine expects it to be.

**Comment by SpaceK33z** [comment]
^ added a failing test case in this PR for it.

**Comment by SpaceK33z** [comment]
& fixed it myself :).

**Comment by mmoreaux** [comment]
Btw, this stuff now lives in the `validation_refactor` branch, so it's easier for us to make changes.

Maybe I should close this PR and make a new one, but then we'll lose the current discussion, ehh.

**Comment by mmoreaux** [comment]
@Daanvdk expanding on this:

> In the code it said that django's full_clean does not check nullability so that we had to implement it ourselves, however during testing I found that I got double errors because django does seem to do it

`full_clean()` raises an error when saving `None` on a `Field()`, but it doesn't raise when saving `None` on a `Field(blank=True)`. But when calling `save()`, Django sends `NULL` to the DB and Postgres says FU. Mindfucks.

I re-enabled the code, refactored is to only act when `blank=True and null=False`, and improved it in general.

**Comment by mmoreaux** [comment]
@Daanvdk I like your usage of `BinderValidationError`s over nameless dicts for collecting and combining the validation violations.

However, I thought

```validation_error = validation_error + e if validation_error else e```

was pretty ugly, so I took the liberty of changing the add stuff so that can simply do

```validation_error += e```

;)

**Comment by mmoreaux** [comment]
Actually, now that we can do this, I think collecting them as an array and then summing them at raise time is even better :P

**Comment by mmoreaux** [comment]
Merged!

**Pull request closed without merging**
