### PR TITLE
Add psycopg2 DateTimeTZRange support

### PR DESCRIPTION
**Pull request by nstylo**
This is not yet tested, please run tests to verify.

NOTE: right now only serialization is supported.
NOTE: please verify that .lower and .upper always contain datetime objects.

### CODE REVIEW

**Comment by nstylo** [comment]
PR still WIP. There need to be some more tests.

**Comment by daanvdk** [comment]
Can you merge with master so that the new github actions CI runs?

**Comment by nstylo** [comment]
Done

**Comment by daanvdk** [comment]
So for some reason with a PR from a fork we cant see the CI in the PR itself.. But in your repo I just saw that it currently fails: https://github.com/nstylo/django-binder/runs/3171292076

**Comment by nstylo** [comment]
Tests are fixed. There are still errors regarding hijack.helpers. But that is unrelated.

**Comment by nstylo** [comment]
@daanvdk can this be merged?

**Comment by daanvdk** [comment]
> Tests are fixed. There are still errors regarding hijack.helpers. But that is unrelated.

I think merging with master should fix this, then the checks should pass and we can look into merging it

**Comment by nstylo** [comment]
@daanvdk tests are passing: https://github.com/nstylo/django-binder/actions/runs/1229553813.

**Pull request merged**
