### PR TITLE
document that a POST can also trigger a DELETE

### PR DESCRIPTION
**Pull request by mdamien**

### CODE REVIEW

**Comment by SpaceK33z** [comment]
I don't get it, how can a POST trigger a DELETE?

**Comment by mdamien** [comment]
as said in the PR, it's only if you provide a `pk`: https://github.com/CodeYellowBV/django-binder/blob/master/binder/views.py#L957

**Comment by SpaceK33z** [comment]
It calls it with `undelete=True`, so isn't this for restoring (undeleting) a model?

**Comment by mdamien** [comment]
oh yes, I misread the code, thanks. Gonna document that then

**Comment by mmoreaux** [comment]
Just to confirm, yes `POST /api/model/:id/` un-soft-deletes (and only that).

**Pull request merged**
